In [1]:
import pandas as pd
from pathlib import Path

# Corrected v2 run completed on 2026-08-26
results_file = Path(
    "/home/sswee/music/llm_responses_4year_v3_detailed/"
    "LLaMA3.1-8B-4year-responses.csv"
)

assert results_file.exists(), (
    f"File not found: {results_file}"
)

results = pd.read_csv(
    results_file,
    dtype={"Patient ID": "string"},
)

assert len(results) == 730
assert results["Patient ID"].is_unique

print("Loaded file:")
print(results_file.resolve())

for prefix in [
    "full_risk_no_ecg",
    "neutral_summary_no_ecg",
    "full_risk_with_ecg",
]:
    status_column = f"{prefix}_generation_status"

    print(f"\n{status_column}:")
    print(
        results[status_column]
        .value_counts(dropna=False)
    )

Loaded file:
/home/sswee/music/llm_responses_4year_v3_detailed/LLaMA3.1-8B-4year-responses.csv

full_risk_no_ecg_generation_status:
full_risk_no_ecg_generation_status
ok    730
Name: count, dtype: int64

neutral_summary_no_ecg_generation_status:
neutral_summary_no_ecg_generation_status
ok    730
Name: count, dtype: int64

full_risk_with_ecg_generation_status:
full_risk_with_ecg_generation_status
ok    730
Name: count, dtype: int64

In [2]:
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)

for prefix in [
    "full_risk_no_ecg",
    "full_risk_with_ecg",
]:
    status_column = f"{prefix}_generation_status"
    response_column = f"{prefix}_raw_response"

    parsed_columns = [
        f"{prefix}_scd_risk",
        f"{prefix}_scd_rationale",
        f"{prefix}_pfd_risk",
        f"{prefix}_pfd_rationale",
    ]

    errors = results.loc[
        results[status_column].eq("format_error"),
        [
            "Patient ID",
            status_column,
            response_column,
            *parsed_columns,
        ],
    ].copy()

    print("\n" + "#" * 100)
    print(prefix)
    print(f"Format errors: {len(errors)}/{len(results)}")

    print("\nMissing parsed fields:")
    print(errors[parsed_columns].isna().sum())

    for _, row in errors.iterrows():
        print("\n" + "=" * 100)
        print("Patient ID:", row["Patient ID"])
        print("-" * 100)
        print(row[response_column])

####################################################################################################
full_risk_no_ecg
Format errors: 0/730

Missing parsed fields:
full_risk_no_ecg_scd_risk         0
full_risk_no_ecg_scd_rationale    0
full_risk_no_ecg_pfd_risk         0
full_risk_no_ecg_pfd_rationale    0
dtype: int64

####################################################################################################
full_risk_with_ecg
Format errors: 0/730

Missing parsed fields:
full_risk_with_ecg_scd_risk         0
full_risk_with_ecg_scd_rationale    0
full_risk_with_ecg_pfd_risk         0
full_risk_with_ecg_pfd_rationale    0
dtype: int64

In [3]:
import re

expected_fields = [
    "SCD_RISK",
    "SCD_RATIONALE",
    "PFD_RISK",
    "PFD_RATIONALE",
]

for prefix in [
    "full_risk_no_ecg",
    "full_risk_with_ecg",
]:
    status_column = f"{prefix}_generation_status"
    response_column = f"{prefix}_raw_response"

    errors = results.loc[
        results[status_column].eq("format_error"),
        ["Patient ID", response_column],
    ].copy()

    for field in expected_fields:
        errors[f"n_{field}"] = (
            errors[response_column]
            .fillna("")
            .str.count(
                rf"(?im)^\s*(?:\d+\.\s*)?{field}\s*:"
            )
        )

    print("\n" + "=" * 100)
    print(prefix)

    display(
        errors[
            [
                "Patient ID",
                "n_SCD_RISK",
                "n_SCD_RATIONALE",
                "n_PFD_RISK",
                "n_PFD_RATIONALE",
            ]
        ]
    )

====================================================================================================
full_risk_no_ecg

Empty DataFrame
Columns: [Patient ID, n_SCD_RISK, n_SCD_RATIONALE, n_PFD_RISK, n_PFD_RATIONALE]
Index: []

====================================================================================================
full_risk_with_ecg

Empty DataFrame
Columns: [Patient ID, n_SCD_RISK, n_SCD_RATIONALE, n_PFD_RISK, n_PFD_RATIONALE]
Index: []

In [4]:
import re
from pathlib import Path

STRUCTURED_FIELDS = (
    "SCD_RISK",
    "SCD_RATIONALE",
    "PFD_RISK",
    "PFD_RATIONALE",
    "CLINICAL_SUMMARY",
)


def extract_all_field_occurrences(text, field):
    """Extract every occurrence of a structured response field."""

    field_alternatives = "|".join(
        re.escape(name)
        for name in STRUCTURED_FIELDS
    )

    pattern = re.compile(
        rf"(?ims)^\s*{re.escape(field)}\s*:\s*(.*?)"
        rf"(?=^\s*(?:{field_alternatives})\s*:|\Z)"
    )

    return [
        match.strip()
        for match in pattern.findall(text or "")
        if match.strip()
    ]


def repair_duplicate_pfd_risk_label(results, prefix):
    """
    Recover a PFD rationale that was incorrectly labeled as a
    second PFD_RISK field.
    """

    status_column = f"{prefix}_generation_status"
    response_column = f"{prefix}_raw_response"

    scd_rationale_column = f"{prefix}_scd_rationale"
    pfd_rationale_column = f"{prefix}_pfd_rationale"

    rationale_only_column = (
        f"{prefix}_rationale_only_response"
    )

    repair_applied_column = (
        f"{prefix}_format_repair_applied"
    )

    repair_reason_column = (
        f"{prefix}_format_repair_reason"
    )

    postprocessed_status_column = (
        f"{prefix}_postprocessed_status"
    )

    results[repair_applied_column] = False
    results[repair_reason_column] = pd.NA

    repair_candidates = (
        results[status_column].eq("format_error")
        & results[pfd_rationale_column].isna()
        & results[response_column].notna()
    )

    for index in results.index[repair_candidates]:
        raw_response = results.at[
            index,
            response_column,
        ]

        pfd_risk_fields = extract_all_field_occurrences(
            raw_response,
            "PFD_RISK",
        )

        # Expected malformed structure:
        # First occurrence  = Low/Moderate/High
        # Second occurrence = intended PFD rationale
        if (
            len(pfd_risk_fields) == 2
            and pfd_risk_fields[0].strip().lower()
                in {"low", "moderate", "high"}
            and pfd_risk_fields[1].strip().lower()
                not in {"low", "moderate", "high"}):
            recovered_rationale = pfd_risk_fields[1]

            results.at[
                index,
                pfd_rationale_column,
            ] = recovered_rationale

            scd_rationale = results.at[
                index,
                scd_rationale_column,
            ]

            if pd.notna(scd_rationale):
                results.at[
                    index,
                    rationale_only_column,
                ] = (
                    f"SCD_RATIONALE: {scd_rationale}\n"
                    f"PFD_RATIONALE: {recovered_rationale}"
                )

            results.at[
                index,
                repair_applied_column,
            ] = True

            results.at[
                index,
                repair_reason_column,
            ] = (
                "Second PFD_RISK field interpreted as "
                "PFD_RATIONALE"
            )

    required_columns = [
        f"{prefix}_scd_risk",
        f"{prefix}_scd_rationale",
        f"{prefix}_pfd_risk",
        f"{prefix}_pfd_rationale",
    ]

    complete_after_processing = (
        results[required_columns]
        .notna()
        .all(axis=1)
    )

    results[postprocessed_status_column] = "unresolved"

    results.loc[
        complete_after_processing,
        postprocessed_status_column,
    ] = "complete"

    return results

for prefix in [
    "full_risk_no_ecg",
    "full_risk_with_ecg",
]:
    results = repair_duplicate_pfd_risk_label(
        results,
        prefix,
    )

In [5]:
for prefix in [
    "full_risk_no_ecg",
    "full_risk_with_ecg",
]:
    print(f"\n{prefix}")

    print("Repairs applied:")
    print(
        results[
            f"{prefix}_format_repair_applied"
        ].value_counts(dropna=False)
    )

    print("Postprocessed status:")
    print(
        results[
            f"{prefix}_postprocessed_status"
        ].value_counts(dropna=False)
    )

full_risk_no_ecg
Repairs applied:
full_risk_no_ecg_format_repair_applied
False    730
Name: count, dtype: int64
Postprocessed status:
full_risk_no_ecg_postprocessed_status
complete    730
Name: count, dtype: int64

full_risk_with_ecg
Repairs applied:
full_risk_with_ecg_format_repair_applied
False    730
Name: count, dtype: int64
Postprocessed status:
full_risk_with_ecg_postprocessed_status
complete    730
Name: count, dtype: int64

In [6]:
from pathlib import Path
import pandas as pd

postprocessed_file = Path(results_file).with_name(
    "LLaMA3.1-8B-4year-responses-postprocessed.csv"
)

# Verify completeness before saving.
for prefix in [
    "full_risk_no_ecg",
    "full_risk_with_ecg",
]:
    required_columns = [
        f"{prefix}_scd_risk",
        f"{prefix}_scd_rationale",
        f"{prefix}_pfd_risk",
        f"{prefix}_pfd_rationale",
    ]

    assert results[
        f"{prefix}_postprocessed_status"
    ].eq("complete").all()

    assert results[required_columns].notna().all().all()

    assert results[
        f"{prefix}_scd_risk"
    ].str.lower().isin(
        ["low", "moderate", "high"]
    ).all()

    assert results[
        f"{prefix}_pfd_risk"
    ].str.lower().isin(
        ["low", "moderate", "high"]
    ).all()

# The neutral-summary condition was already completely valid.
assert results[
    "neutral_summary_no_ecg_generation_status"
].eq("ok").all()

results.to_csv(
    postprocessed_file,
    index=False,
    na_rep="",
)

# Reload and verify the saved artifact.
saved_results = pd.read_csv(
    postprocessed_file,
    dtype={"Patient ID": "string"},
)

assert len(saved_results) == 730
assert saved_results["Patient ID"].is_unique

for prefix in [
    "full_risk_no_ecg",
    "full_risk_with_ecg",
]:
    assert saved_results[
        f"{prefix}_postprocessed_status"
    ].eq("complete").all()

print("Saved and verified:")
print(postprocessed_file.resolve())

Saved and verified:
/home/sswee/music/llm_responses_4year_v3_detailed/LLaMA3.1-8B-4year-responses-postprocessed.csv

In [8]:
import pandas as pd
from pathlib import Path

results_file_3b = Path(
    "/home/sswee/music/llm_responses_4year_v3_detailed/"
    "LLaMA3.2-3B-4year-responses.csv"
)

assert results_file_3b.exists(), (
    f"File not found: {results_file_3b}"
)

results_3b = pd.read_csv(
    results_file_3b,
    dtype={"Patient ID": "string"},
)

assert len(results_3b) == 730
assert results_3b["Patient ID"].is_unique

print("Loaded file:")
print(results_file_3b.resolve())

for prefix in [
    "full_risk_no_ecg",
    "neutral_summary_no_ecg",
    "full_risk_with_ecg",
]:
    status_column = f"{prefix}_generation_status"

    print(f"\n{status_column}:")
    print(
        results_3b[status_column]
        .value_counts(dropna=False)
    )

Loaded file:
/home/sswee/music/llm_responses_4year_v3_detailed/LLaMA3.2-3B-4year-responses.csv

full_risk_no_ecg_generation_status:
full_risk_no_ecg_generation_status
ok              678
format_error     52
Name: count, dtype: int64

neutral_summary_no_ecg_generation_status:
neutral_summary_no_ecg_generation_status
ok    730
Name: count, dtype: int64

full_risk_with_ecg_generation_status:
full_risk_with_ecg_generation_status
ok              699
format_error     31
Name: count, dtype: int64

In [16]:
import re
import pandas as pd


STRUCTURED_FIELDS = (
    "SCD_RISK",
    "SCD_RATIONALE",
    "PFD_RISK",
    "PFD_RATIONALE",
    "CLINICAL_SUMMARY",
)

ALLOWED_RISKS = {
    "low",
    "moderate",
    "high",
}


def extract_all_field_occurrences(
    text,
    field,
):
    """
    Extract every nonempty occurrence of a structured field.

    Values may span multiple lines. An occurrence ends when the
    next recognized structured-field header begins or the response
    ends.
    """

    field_alternatives = "|".join(
        re.escape(name)
        for name in STRUCTURED_FIELDS
    )

    pattern = re.compile(
        rf"(?ims)"
        rf"^\s*(?:\d+\.\s*)?"
        rf"{re.escape(field)}\s*:\s*"
        rf"(.*?)"
        rf"(?="
        rf"^\s*(?:\d+\.\s*)?"
        rf"(?:{field_alternatives})\s*:"
        rf"|\Z"
        rf")"
    )

    return [
        occurrence.strip()
        for occurrence in pattern.findall(text or "")
        if occurrence.strip()
    ]


def normalize_exact_risk(value):
    """
    Return a normalized risk category only when the complete field
    contains a single allowed risk value.
    """

    if not value:
        return None

    match = re.fullmatch(
        r"\s*\[?\s*(low|moderate|high)\s*\]?\s*",
        str(value),
        flags=re.IGNORECASE,
    )

    if not match:
        return None

    return match.group(1).lower()


def repair_duplicate_pfd_risk_header(
    dataframe,
    prefix,
):
    """
    Repair the exact observed formatting error:

        PFD_RISK: <Low, Moderate, or High>
        PFD_RISK: <detailed rationale>

    The second PFD_RISK value is relabeled as PFD_RATIONALE only
    when all expected field counts and values make the intended
    structure unambiguous.

    The raw response and original generation status are unchanged.
    """

    results = dataframe

    status_column = (
        f"{prefix}_generation_status"
    )

    response_column = (
        f"{prefix}_raw_response"
    )

    scd_risk_column = (
        f"{prefix}_scd_risk"
    )

    scd_rationale_column = (
        f"{prefix}_scd_rationale"
    )

    pfd_risk_column = (
        f"{prefix}_pfd_risk"
    )

    pfd_rationale_column = (
        f"{prefix}_pfd_rationale"
    )

    label_only_column = (
        f"{prefix}_label_only_response"
    )

    rationale_only_column = (
        f"{prefix}_rationale_only_response"
    )

    repair_applied_column = (
        f"{prefix}_format_repair_applied"
    )

    repair_reason_column = (
        f"{prefix}_format_repair_reason"
    )

    postprocessed_status_column = (
        f"{prefix}_postprocessed_status"
    )

    # Reset post-processing fields so rerunning the cell cannot
    # retain stale repair results from an earlier notebook state.

    results[repair_applied_column] = False
    results[repair_reason_column] = pd.NA
    results[postprocessed_status_column] = "unresolved"

    repair_candidates = (
        results[status_column].eq("format_error")
        & results[response_column].notna()
    )

    for index in results.index[repair_candidates]:
        raw_response = str(
            results.at[
                index,
                response_column,
            ]
        )

        scd_risk_occurrences = (
            extract_all_field_occurrences(
                raw_response,
                "SCD_RISK",
            )
        )

        scd_rationale_occurrences = (
            extract_all_field_occurrences(
                raw_response,
                "SCD_RATIONALE",
            )
        )

        pfd_risk_occurrences = (
            extract_all_field_occurrences(
                raw_response,
                "PFD_RISK",
            )
        )

        pfd_rationale_occurrences = (
            extract_all_field_occurrences(
                raw_response,
                "PFD_RATIONALE",
            )
        )

        exact_error_structure = (
            len(scd_risk_occurrences) == 1
            and len(scd_rationale_occurrences) == 1
            and len(pfd_risk_occurrences) == 2
            and len(pfd_rationale_occurrences) == 0
        )

        if not exact_error_structure:
            continue

        first_pfd_value = pfd_risk_occurrences[0]
        second_pfd_value = pfd_risk_occurrences[1]

        first_value_is_risk = (
            normalize_exact_risk(first_pfd_value)
            is not None
        )

        second_value_is_not_risk = (
            normalize_exact_risk(second_pfd_value)
            is None
        )

        if not (
            first_value_is_risk
            and second_value_is_not_risk
        ):
            continue

        # The second PFD_RISK occurrence contains the complete
        # intended PFD rationale.

        recovered_pfd_rationale = second_pfd_value

        results.at[
            index,
            pfd_rationale_column,
        ] = recovered_pfd_rationale

        scd_risk = results.at[
            index,
            scd_risk_column,
        ]

        pfd_risk = results.at[
            index,
            pfd_risk_column,
        ]

        scd_rationale = results.at[
            index,
            scd_rationale_column,
        ]

        # Reconstruct the derived ablation representations.

        if (
            pd.notna(scd_risk)
            and pd.notna(pfd_risk)
        ):
            results.at[
                index,
                label_only_column,
            ] = (
                f"SCD_RISK: "
                f"{str(scd_risk).title()}\n"
                f"PFD_RISK: "
                f"{str(pfd_risk).title()}"
            )

        if pd.notna(scd_rationale):
            results.at[
                index,
                rationale_only_column,
            ] = (
                f"SCD_RATIONALE: "
                f"{scd_rationale}\n"
                f"PFD_RATIONALE: "
                f"{recovered_pfd_rationale}"
            )

        results.at[
            index,
            repair_applied_column,
        ] = True

        results.at[
            index,
            repair_reason_column,
        ] = (
            "Second PFD_RISK field interpreted as "
            "PFD_RATIONALE"
        )

    required_columns = [
        scd_risk_column,
        scd_rationale_column,
        pfd_risk_column,
        pfd_rationale_column,
    ]

    fields_complete = (
        results[required_columns]
        .notna()
        .all(axis=1)
    )

    valid_scd_risk = (
        results[scd_risk_column]
        .astype("string")
        .str.lower()
        .isin(ALLOWED_RISKS)
    )

    valid_pfd_risk = (
        results[pfd_risk_column]
        .astype("string")
        .str.lower()
        .isin(ALLOWED_RISKS)
    )

    complete_after_processing = (
        fields_complete
        & valid_scd_risk
        & valid_pfd_risk
    )

    results.loc[
        complete_after_processing,
        postprocessed_status_column,
    ] = "complete"

    return results

In [17]:
EXPECTED_REPAIR_COUNTS = {
    "full_risk_no_ecg": 52,
    "full_risk_with_ecg": 31,
}


for prefix in [
    "full_risk_no_ecg",
    "full_risk_with_ecg",
]:
    results_3b = repair_duplicate_pfd_risk_header(
        results_3b,
        prefix,
    )


for prefix, expected_repairs in (
    EXPECTED_REPAIR_COUNTS.items()
):
    status_column = (
        f"{prefix}_generation_status"
    )

    repair_applied_column = (
        f"{prefix}_format_repair_applied"
    )

    repair_reason_column = (
        f"{prefix}_format_repair_reason"
    )

    postprocessed_status_column = (
        f"{prefix}_postprocessed_status"
    )

    pfd_rationale_column = (
        f"{prefix}_pfd_rationale"
    )

    original_format_errors = int(
        results_3b[
            status_column
        ].eq("format_error").sum()
    )

    repairs_applied = int(
        results_3b[
            repair_applied_column
        ].sum()
    )

    unresolved = int(
        results_3b[
            postprocessed_status_column
        ].ne("complete").sum()
    )

    print("\n" + "=" * 80)
    print(prefix)
    print(
        "Original format errors:",
        original_format_errors,
    )
    print(
        "Expected repairs:",
        expected_repairs,
    )
    print(
        "Repairs applied:",
        repairs_applied,
    )
    print(
        "Unresolved responses:",
        unresolved,
    )

    # Confirm that the expected results file was loaded.

    assert (
        original_format_errors
        == expected_repairs
    ), (
        f"Unexpected format-error count for {prefix}: "
        f"expected {expected_repairs}, "
        f"observed {original_format_errors}"
    )

    # Every malformed response must match the single,
    # prespecified repair rule.

    assert (
        repairs_applied
        == original_format_errors
    ), (
        f"Not every format error was repaired for {prefix}"
    )

    # No originally valid response may be modified.

    assert not (
        results_3b[repair_applied_column]
        & ~results_3b[status_column].eq(
            "format_error"
        )
    ).any(), (
        f"A valid response was modified for {prefix}"
    )

    # Every repaired row must document the same rule.

    assert (
        results_3b.loc[
            results_3b[repair_applied_column],
            repair_reason_column,
        ]
        .eq(
            "Second PFD_RISK field interpreted as "
            "PFD_RATIONALE"
        )
        .all()
    )

    # All required fields must now be complete.

    assert unresolved == 0

    assert results_3b[
        postprocessed_status_column
    ].eq("complete").all()

    assert results_3b[
        pfd_rationale_column
    ].notna().all()


# The neutral-summary condition required no repair.

assert results_3b[
    "neutral_summary_no_ecg_generation_status"
].eq("ok").all()


print("\nPASS: all 83 formatting errors were repaired.")
print(
    "The original raw responses and generation-status "
    "columns were not modified."
)

================================================================================
full_risk_no_ecg
Original format errors: 52
Expected repairs: 52
Repairs applied: 52
Unresolved responses: 0

================================================================================
full_risk_with_ecg
Original format errors: 31
Expected repairs: 31
Repairs applied: 31
Unresolved responses: 0

PASS: all 83 formatting errors were repaired.
The original raw responses and generation-status columns were not modified.

In [18]:
from pathlib import Path
import hashlib
import pandas as pd


postprocessed_file_3b = (
    results_file_3b.with_name(
        "LLaMA3.2-3B-4year-responses-postprocessed.csv"
    )
)


# Save without replacing the original response file.

results_3b.to_csv(
    postprocessed_file_3b,
    index=False,
    na_rep="",
)


# Reload the original and postprocessed files using consistent
# string handling.

original_saved_results_3b = pd.read_csv(
    results_file_3b,
    dtype={"Patient ID": "string"},
    keep_default_na=False,
)

saved_results_3b = pd.read_csv(
    postprocessed_file_3b,
    dtype={"Patient ID": "string"},
    keep_default_na=False,
)


# Basic saved-file integrity.

assert len(saved_results_3b) == 730
assert saved_results_3b["Patient ID"].is_unique

assert (
    saved_results_3b["Patient ID"]
    .equals(
        original_saved_results_3b["Patient ID"]
    )
)


# Confirm that every full-risk response is complete after
# deterministic post-processing.

for prefix, expected_repairs in (
    EXPECTED_REPAIR_COUNTS.items()
):
    postprocessed_status_column = (
        f"{prefix}_postprocessed_status"
    )

    repair_applied_column = (
        f"{prefix}_format_repair_applied"
    )

    required_columns = [
        f"{prefix}_scd_risk",
        f"{prefix}_scd_rationale",
        f"{prefix}_pfd_risk",
        f"{prefix}_pfd_rationale",
    ]

    assert saved_results_3b[
        postprocessed_status_column
    ].eq("complete").all()

    assert (
        saved_results_3b[
            repair_applied_column
        ]
        .astype(str)
        .str.lower()
        .eq("true")
        .sum()
        == expected_repairs
    )

    for column in required_columns:
        assert saved_results_3b[
            column
        ].astype(str).str.strip().ne("").all()

    assert saved_results_3b[
        f"{prefix}_scd_risk"
    ].str.lower().isin(
        ALLOWED_RISKS
    ).all()

    assert saved_results_3b[
        f"{prefix}_pfd_risk"
    ].str.lower().isin(
        ALLOWED_RISKS
    ).all()


# Verify that the raw LLM responses were preserved byte-for-byte
# at the cell-value level.

raw_response_columns = [
    "full_risk_no_ecg_raw_response",
    "neutral_summary_no_ecg_raw_response",
    "full_risk_with_ecg_raw_response",
]

for column in raw_response_columns:
    assert (
        saved_results_3b[column]
        .equals(
            original_saved_results_3b[column]
        )
    ), (
        f"Raw-response content changed in {column}"
    )


# Verify that the original generation-status fields were preserved.

generation_status_columns = [
    "full_risk_no_ecg_generation_status",
    "neutral_summary_no_ecg_generation_status",
    "full_risk_with_ecg_generation_status",
]

for column in generation_status_columns:
    assert (
        saved_results_3b[column]
        .equals(
            original_saved_results_3b[column]
        )
    ), (
        f"Original generation status changed in {column}"
    )


def calculate_sha256(file_path):
    digest = hashlib.sha256()

    with Path(file_path).open("rb") as file_handle:
        for block in iter(
            lambda: file_handle.read(
                1024 * 1024
            ),
            b"",
        ):
            digest.update(block)

    return digest.hexdigest()


postprocessed_sha256 = calculate_sha256(
    postprocessed_file_3b
)


print("Saved and verified:")
print(postprocessed_file_3b.resolve())

print("\nPostprocessed file SHA-256:")
print(postprocessed_sha256)

Saved and verified:
/home/sswee/music/llm_responses_4year_v3_detailed/LLaMA3.2-3B-4year-responses-postprocessed.csv

Postprocessed file SHA-256:
26ec77e926ca7a130662dfcc1961d7dedf6f9f6742eab22b45aade74dd5d0d5f